// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0h5ZChqgE7cj-oPXiuaG_vraPW7HOOY4',
    appId: '1:426222909305:web:db16d874ae22a076eae1a8',
    messagingSenderId: '426222909305',
    projectId: 'connectools-f1494',
    authDomain: 'connectools-f1494.firebaseapp.com',
    storageBucket: 'connectools-f1494.firebasestorage.app',
    measurementId: 'G-ZBWFRTZS3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzz7TtpEif7Jfg-mWa0M4NzslbUYtPmZI',
    appId: '1:426222909305:android:c7b92c825318dd1feae1a8',
    messagingSenderId: '426222909305',
    projectId: 'connectools-f1494',
    storageBucket: 'connectools-f1494.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd6j2fZARUeOtrdyweiFcMQi4Rnuue948',
    appId: '1:426222909305:ios:17665e0e30bc7f2feae1a8',
    messagingSenderId: '426222909305',
    projectId: 'connectools-f1494',
    storageBucket: 'connectools-f1494.firebasestorage.app',
    iosBundleId: 'com.example.communityToolsSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd6j2fZARUeOtrdyweiFcMQi4Rnuue948',
    appId: '1:426222909305:ios:17665e0e30bc7f2feae1a8',
    messagingSenderId: '426222909305',
    projectId: 'connectools-f1494',
    storageBucket: 'connectools-f1494.firebasestorage.app',
    iosBundleId: 'com.example.communityToolsSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0h5ZChqgE7cj-oPXiuaG_vraPW7HOOY4',
    appId: '1:426222909305:web:28b562a736526d25eae1a8',
    messagingSenderId: '426222909305',
    projectId: 'connectools-f1494',
    authDomain: 'connectools-f1494.firebaseapp.com',
    storageBucket: 'connectools-f1494.firebasestorage.app',
    measurementId: 'G-V1KFYKNTGP',
  );
}
